# Site settings
title: Softlinks Solutions
description: Purpose-built software crafted by experts.
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "https://willianjusten.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Softlinks Solutions
user_description: Purpose-built software crafted by experts.
user_title: Purpose-built software crafted by experts.
email: softlinkssolutions@gmail.com
twitter_username: softlinkssolutions
github_username:  softlinkssolutions
facebook_username: Softlinks


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
# links:
#   - title: Home
#     url: /
#   - title: Series
#     url: /series
#   - title: Tags
#     url: /tags
#   - title: About Me
#     url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
